name: Publish NuGet Package

on:
  push:
    tags:
      - "*"

jobs:
  ubuntu-latest:
    name: Publish nuget
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for trusted publishing
      contents: read    
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          flavor: |
            latest=false
          sep-tags: ";"
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Setup dotnet
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 10.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output output /property:Version="${{ steps.meta.outputs.version }}"

      - name: NuGet login
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}        

      - name: Push
        run: dotnet nuget push output/*.nupkg --skip-duplicate --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
